<a href="https://colab.research.google.com/github/DipaliDhonnar/python/blob/main/AirLine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [102]:
import pandas as pd
import  numpy as np
#Load the CSV file into a Pandas DataFrame.
df=pd.read_csv("/content/drive/MyDrive/python database/airline_passengers_indian.csv")

df

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status
0,1,Aarav,Sharma,25,Male,AI101,Mumbai,London,500,Economy,Confirmed
1,2,Vihaan,Verma,30,Male,BA202,Delhi,New York,750,Business,Cancelled
2,3,Vivaan,Patel,45,Male,DL303,Bangalore,Los Angeles,600,Economy,Confirmed
3,4,Anaya,Desai,28,Female,EK404,Chennai,Dubai,1200,First,Confirmed
4,5,Myra,Iyer,34,Female,QR505,Kolkata,Tokyo,900,Business,On Hold
5,6,Aryan,Nair,22,Male,LH606,Hyderabad,Munich,850,Economy,Confirmed
6,7,Ishaan,Mehta,40,Male,AF707,Pune,Rome,950,First,Cancelled
7,8,Kabir,Rao,38,Male,SQ808,Ahmedabad,Hong Kong,1100,Business,Confirmed
8,9,Saanvi,Joshi,29,Female,UA909,Lucknow,San Francisco,700,Economy,On Hold
9,10,Aadhya,Bhat,27,Female,AI110,Jaipur,Singapore,650,Economy,Confirmed
10,11,Advait,Kapoor,32,Male,BA211,Mumbai,London,720,Business,Confirmed
11,12,Rudra,Chopra,26,Male,DL322,Delhi,New York,580,Economy,Cancelled
12,13,Pari,Malhotra,50,Female,EK433,Bangalore,Los Angeles,1300,First,Confirmed
13,14,Kiaan,Jain,31,Male,QR544,Chennai,Dubai,890,Business,On Hold
14,15,Tanish,Agarwal,35,Male,LH633,Kolkata,Tokyo,800,Economy,Confirmed
15,16,Riya,Bose,23,Female,AF722,Hyderabad,Munich,970,First,Confirmed
16,17,Krishna,Das,36,Male,SQ833,Pune,Rome,1150,Business,On Hold
17,18,Shaurya,Saxena,41,Male,UA944,Ahmedabad,Hong Kong,730,Economy,Confirmed
18,19,Tanvi,Chatterjee,48,Female,AI123,Lucknow,San Francisco,670,Economy,Confirmed
19,20,Arjun,Gupta,33,Male,QR567,Jaipur,Singapore,910,Business,On Hold

In [103]:
#	Display the first 5 rows of the DataFrame.
df.head(5)

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status
0,1,Aarav,Sharma,25,Male,AI101,Mumbai,London,500,Economy,Confirmed
1,2,Vihaan,Verma,30,Male,BA202,Delhi,New York,750,Business,Cancelled
2,3,Vivaan,Patel,45,Male,DL303,Bangalore,Los Angeles,600,Economy,Confirmed
3,4,Anaya,Desai,28,Female,EK404,Chennai,Dubai,1200,First,Confirmed
4,5,Myra,Iyer,34,Female,QR505,Kolkata,Tokyo,900,Business,On Hold

In [104]:
#Display the last 5 rows of the DataFrame.
df.tail(5)

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status
15,16,Riya,Bose,23,Female,AF722,Hyderabad,Munich,970,First,Confirmed
16,17,Krishna,Das,36,Male,SQ833,Pune,Rome,1150,Business,On Hold
17,18,Shaurya,Saxena,41,Male,UA944,Ahmedabad,Hong Kong,730,Economy,Confirmed
18,19,Tanvi,Chatterjee,48,Female,AI123,Lucknow,San Francisco,670,Economy,Confirmed
19,20,Arjun,Gupta,33,Male,QR567,Jaipur,Singapore,910,Business,On Hold

In [105]:
#4.	Get the total number of rows and columns in the DataFrame.
df.shape

(20, 11)

In [106]:
#Display all column names in the dataset.
list(df.columns)

['PassengerID',
 'FirstName',
 'LastName',
 'Age',
 'Gender',
 'FlightNumber',
 'Departure',
 'Destination',
 'TicketPrice',
 'SeatClass',
 'Status']

In [107]:
#Get summary statistics of numerical columns.
df.describe()

       PassengerID        Age  TicketPrice
count     20.00000  20.000000    20.000000
mean      10.50000  33.650000   846.000000
std        5.91608   8.034629   218.352684
min        1.00000  22.000000   500.000000
25%        5.75000  27.750000   692.500000
50%       10.50000  32.500000   825.000000
75%       15.25000  38.500000   955.000000
max       20.00000  50.000000  1300.000000

In [108]:
#Check for missing values in the dataset.
df.isnull().sum()

PassengerID     0
FirstName       0
LastName        0
Age             0
Gender          0
FlightNumber    0
Departure       0
Destination     0
TicketPrice     0
SeatClass       0
Status          0
dtype: int64

In [157]:
#Select only the 'FirstName' and 'LastName' columns.
df[["FirstName",
    "LastName"]]

   FirstName    LastName
0      Aarav      Sharma
1     Vihaan       Verma
2     Vivaan       Patel
3      Anaya       Desai
4       Myra        Iyer
5      Aryan        Nair
6     Ishaan       Mehta
7      Kabir         Rao
8     Saanvi       Joshi
9     Aadhya        Bhat
10    Advait      Kapoor
11     Rudra      Chopra
12      Pari    Malhotra
13     Kiaan        Jain
14    Tanish     Agarwal
15      Riya        Bose
16   Krishna         Das
17   Shaurya      Saxena
18     Tanvi  Chatterjee
19     Arjun       Gupta

In [110]:
#Retrieve the ticket price of the 10th passenger.
df.iloc[9,8]

np.int64(650)

In [111]:
#	Find all passengers whose ticket price is greater than ₹900.
df[df["TicketPrice"]>900]

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status
3,4,Anaya,Desai,28,Female,EK404,Chennai,Dubai,1200,First,Confirmed
6,7,Ishaan,Mehta,40,Male,AF707,Pune,Rome,950,First,Cancelled
7,8,Kabir,Rao,38,Male,SQ808,Ahmedabad,Hong Kong,1100,Business,Confirmed
12,13,Pari,Malhotra,50,Female,EK433,Bangalore,Los Angeles,1300,First,Confirmed
15,16,Riya,Bose,23,Female,AF722,Hyderabad,Munich,970,First,Confirmed
16,17,Krishna,Das,36,Male,SQ833,Pune,Rome,1150,Business,On Hold
19,20,Arjun,Gupta,33,Male,QR567,Jaipur,Singapore,910,Business,On Hold

In [112]:
#Count the number of passengers in each seat class.
#df.groupby("SeatClass")["PassengerID"].count()
df["SeatClass"].value_counts()

SeatClass
Economy     9
Business    7
First       4
Name: count, dtype: int64

In [113]:
#	Find the passenger with the highest ticket price.
df.nlargest(1,"TicketPrice")

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status
12,13,Pari,Malhotra,50,Female,EK433,Bangalore,Los Angeles,1300,First,Confirmed

In [114]:
#Get the average ticket price of all passengers.
df["TicketPrice"].mean()

np.float64(846.0)

In [158]:
#Sort the passengers by ticket price in descending order.
df.sort_values("TicketPrice",ascending=False).head()

,index,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status,Discount,FinalPrice,AgeGroup,HighValue,AboveAverage
12,12,13,Pari,Malhotra,50,Female,EK433,Bangalore,Los Angeles,1300,First,Confirmed,130.0,1170.0,Senior,Yes,Yes
3,3,4,Anaya,Desai,28,Female,EK404,Chennai,Dubai,1200,First,Confirmed,120.0,1080.0,Young,Yes,Yes
16,16,17,Krishna,Das,36,Male,SQ833,Pune,Rome,1150,Business,Pending,115.0,1035.0,Adult,Yes,Yes
7,7,8,Kabir,Rao,38,Male,SQ808,Ahmedabad,Hong Kong,1100,Business,Confirmed,110.0,990.0,Adult,Yes,Yes
15,15,16,Riya,Bose,23,Female,AF722,Hyderabad,Munich,970,First,Confirmed,97.0,873.0,Young,No,Yes

In [116]:
#List all passengers who booked a 'First' class ticket.
df[df['SeatClass']=="First"]

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status
3,4,Anaya,Desai,28,Female,EK404,Chennai,Dubai,1200,First,Confirmed
6,7,Ishaan,Mehta,40,Male,AF707,Pune,Rome,950,First,Cancelled
12,13,Pari,Malhotra,50,Female,EK433,Bangalore,Los Angeles,1300,First,Confirmed
15,16,Riya,Bose,23,Female,AF722,Hyderabad,Munich,970,First,Confirmed

In [117]:
#Add a new column 'Discount' where each passenger gets a 10% discount on their ticket price.
df["Discount"] = (df['TicketPrice']*10)/100
df.head()

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status,Discount
0,1,Aarav,Sharma,25,Male,AI101,Mumbai,London,500,Economy,Confirmed,50.0
1,2,Vihaan,Verma,30,Male,BA202,Delhi,New York,750,Business,Cancelled,75.0
2,3,Vivaan,Patel,45,Male,DL303,Bangalore,Los Angeles,600,Economy,Confirmed,60.0
3,4,Anaya,Desai,28,Female,EK404,Chennai,Dubai,1200,First,Confirmed,120.0
4,5,Myra,Iyer,34,Female,QR505,Kolkata,Tokyo,900,Business,On Hold,90.0

In [118]:
#Create a new column 'FinalPrice' which is TicketPrice - Discount.
df['FinalPrice']=df["TicketPrice"]-df["Discount"]
df.head(2)

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status,Discount,FinalPrice
0,1,Aarav,Sharma,25,Male,AI101,Mumbai,London,500,Economy,Confirmed,50.0,450.0
1,2,Vihaan,Verma,30,Male,BA202,Delhi,New York,750,Business,Cancelled,75.0,675.0

In [119]:
#Create a new column 'AgeGroup' with categories:o	'Young' (Below 30)o	'Adult' (30-45)o	'Senior' (Above 45).
df['AgeGroup'] = df['Age'].apply(lambda x: 'Senior' if x > 45 else ('Adult' if 30 <= x <= 45 else 'Young'))
df.head(2)

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status,Discount,FinalPrice,AgeGroup
0,1,Aarav,Sharma,25,Male,AI101,Mumbai,London,500,Economy,Confirmed,50.0,450.0,Young
1,2,Vihaan,Verma,30,Male,BA202,Delhi,New York,750,Business,Cancelled,75.0,675.0,Adult

In [120]:
#Create a new column 'HighValue' with 'Yes' if TicketPrice > ₹1000, else 'No'.
df["HighValue"]=df["TicketPrice"].apply(lambda i :("Yes") if i>1000 else("No"))

In [121]:
#	Find the average ticket price per seat class.
df.groupby("SeatClass")["TicketPrice"].mean()

SeatClass
Business     917.142857
Economy      675.555556
First       1105.000000
Name: TicketPrice, dtype: float64

In [122]:
#Count the number of passengers in each 'AgeGroup'.
df["AgeGroup"].value_counts()

AgeGroup
Adult     11
Young      7
Senior     2
Name: count, dtype: int64

In [123]:
# Find the highest ticket price in each seat class.
df.groupby("SeatClass")["TicketPrice"].max()

SeatClass
Business    1150
Economy      850
First       1300
Name: TicketPrice, dtype: int64

In [124]:
#Find the lowest ticket price in each seat class.
df.groupby("SeatClass")["TicketPrice"].min()

SeatClass
Business    720
Economy     500
First       950
Name: TicketPrice, dtype: int64

In [125]:
#Find the passenger with the highest age.
df.nlargest(1,"Age")

,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status,Discount,FinalPrice,AgeGroup,HighValue
12,13,Pari,Malhotra,50,Female,EK433,Bangalore,Los Angeles,1300,First,Confirmed,130.0,1170.0,Senior,Yes

In [126]:
#Count the number of passengers with a 'Confirmed' booking.
df[df["Status"]=="Confirmed"]["PassengerID"].count()

np.int64(12)

In [127]:
#Find the average ticket price of passengers in Business Class.
df[df["SeatClass"]=="Business"]["TicketPrice"].mean()

np.float64(917.1428571428571)

In [128]:
#Find the highest ticket price for each flight.
df.groupby('FlightNumber')['TicketPrice'].max()

FlightNumber
AF707     950
AF722     970
AI101     500
AI110     650
AI123     670
BA202     750
BA211     720
DL303     600
DL322     580
EK404    1200
EK433    1300
LH606     850
LH633     800
QR505     900
QR544     890
QR567     910
SQ808    1100
SQ833    1150
UA909     700
UA944     730
Name: TicketPrice, dtype: int64

In [129]:
#Remove the 'Gender' column from the dataset.
df.drop("Gender" ,axis=1)

,PassengerID,FirstName,LastName,Age,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status,Discount,FinalPrice,AgeGroup,HighValue
0,1,Aarav,Sharma,25,AI101,Mumbai,London,500,Economy,Confirmed,50.0,450.0,Young,No
1,2,Vihaan,Verma,30,BA202,Delhi,New York,750,Business,Cancelled,75.0,675.0,Adult,No
2,3,Vivaan,Patel,45,DL303,Bangalore,Los Angeles,600,Economy,Confirmed,60.0,540.0,Adult,No
3,4,Anaya,Desai,28,EK404,Chennai,Dubai,1200,First,Confirmed,120.0,1080.0,Young,Yes
4,5,Myra,Iyer,34,QR505,Kolkata,Tokyo,900,Business,On Hold,90.0,810.0,Adult,No
5,6,Aryan,Nair,22,LH606,Hyderabad,Munich,850,Economy,Confirmed,85.0,765.0,Young,No
6,7,Ishaan,Mehta,40,AF707,Pune,Rome,950,First,Cancelled,95.0,855.0,Adult,No
7,8,Kabir,Rao,38,SQ808,Ahmedabad,Hong Kong,1100,Business,Confirmed,110.0,990.0,Adult,Yes
8,9,Saanvi,Joshi,29,UA909,Lucknow,San Francisco,700,Economy,On Hold,70.0,630.0,Young,No
9,10,Aadhya,Bhat,27,AI110,Jaipur,Singapore,650,Economy,Confirmed,65.0,585.0,Young,No
10,11,Advait,Kapoor,32,BA211,Mumbai,London,720,Business,Confirmed,72.0,648.0,Adult,No
11,12,Rudra,Chopra,26,DL322,Delhi,New York,580,Economy,Cancelled,58.0,522.0,Young,No
12,13,Pari,Malhotra,50,EK433,Bangalore,Los Angeles,1300,First,Confirmed,130.0,1170.0,Senior,Yes
13,14,Kiaan,Jain,31,QR544,Chennai,Dubai,890,Business,On Hold,89.0,801.0,Adult,No
14,15,Tanish,Agarwal,35,LH633,Kolkata,Tokyo,800,Economy,Confirmed,80.0,720.0,Adult,No
15,16,Riya,Bose,23,AF722,Hyderabad,Munich,970,First,Confirmed,97.0,873.0,Young,No
16,17,Krishna,Das,36,SQ833,Pune,Rome,1150,Business,On Hold,115.0,1035.0,Adult,Yes
17,18,Shaurya,Saxena,41,UA944,Ahmedabad,Hong Kong,730,Economy,Confirmed,73.0,657.0,Adult,No
18,19,Tanvi,Chatterjee,48,AI123,Lucknow,San Francisco,670,Economy,Confirmed,67.0,603.0,Senior,No
19,20,Arjun,Gupta,33,QR567,Jaipur,Singapore,910,Business,On Hold,91.0,819.0,Adult,No

In [130]:
#Reset the index of the dataset.
df = df.reset_index()
df

,index,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status,Discount,FinalPrice,AgeGroup,HighValue
0,0,1,Aarav,Sharma,25,Male,AI101,Mumbai,London,500,Economy,Confirmed,50.0,450.0,Young,No
1,1,2,Vihaan,Verma,30,Male,BA202,Delhi,New York,750,Business,Cancelled,75.0,675.0,Adult,No
2,2,3,Vivaan,Patel,45,Male,DL303,Bangalore,Los Angeles,600,Economy,Confirmed,60.0,540.0,Adult,No
3,3,4,Anaya,Desai,28,Female,EK404,Chennai,Dubai,1200,First,Confirmed,120.0,1080.0,Young,Yes
4,4,5,Myra,Iyer,34,Female,QR505,Kolkata,Tokyo,900,Business,On Hold,90.0,810.0,Adult,No
5,5,6,Aryan,Nair,22,Male,LH606,Hyderabad,Munich,850,Economy,Confirmed,85.0,765.0,Young,No
6,6,7,Ishaan,Mehta,40,Male,AF707,Pune,Rome,950,First,Cancelled,95.0,855.0,Adult,No
7,7,8,Kabir,Rao,38,Male,SQ808,Ahmedabad,Hong Kong,1100,Business,Confirmed,110.0,990.0,Adult,Yes
8,8,9,Saanvi,Joshi,29,Female,UA909,Lucknow,San Francisco,700,Economy,On Hold,70.0,630.0,Young,No
9,9,10,Aadhya,Bhat,27,Female,AI110,Jaipur,Singapore,650,Economy,Confirmed,65.0,585.0,Young,No
10,10,11,Advait,Kapoor,32,Male,BA211,Mumbai,London,720,Business,Confirmed,72.0,648.0,Adult,No
11,11,12,Rudra,Chopra,26,Male,DL322,Delhi,New York,580,Economy,Cancelled,58.0,522.0,Young,No
12,12,13,Pari,Malhotra,50,Female,EK433,Bangalore,Los Angeles,1300,First,Confirmed,130.0,1170.0,Senior,Yes
13,13,14,Kiaan,Jain,31,Male,QR544,Chennai,Dubai,890,Business,On Hold,89.0,801.0,Adult,No
14,14,15,Tanish,Agarwal,35,Male,LH633,Kolkata,Tokyo,800,Economy,Confirmed,80.0,720.0,Adult,No
15,15,16,Riya,Bose,23,Female,AF722,Hyderabad,Munich,970,First,Confirmed,97.0,873.0,Young,No
16,16,17,Krishna,Das,36,Male,SQ833,Pune,Rome,1150,Business,On Hold,115.0,1035.0,Adult,Yes
17,17,18,Shaurya,Saxena,41,Male,UA944,Ahmedabad,Hong Kong,730,Economy,Confirmed,73.0,657.0,Adult,No
18,18,19,Tanvi,Chatterjee,48,Female,AI123,Lucknow,San Francisco,670,Economy,Confirmed,67.0,603.0,Senior,No
19,19,20,Arjun,Gupta,33,Male,QR567,Jaipur,Singapore,910,Business,On Hold,91.0,819.0,Adult,No

In [139]:
#Replace all 'On Hold' statuses with 'Pending'.
df["Status"]=df["Status"].replace("On Hold","Pending")
df.tail(5)

,index,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status,Discount,FinalPrice,AgeGroup,HighValue,AboveAverage
15,15,16,Riya,Bose,23,Female,AF722,Hyderabad,Munich,970,First,Confirmed,97.0,873.0,Young,No,Yes
16,16,17,Krishna,Das,36,Male,SQ833,Pune,Rome,1150,Business,Pending,115.0,1035.0,Adult,Yes,Yes
17,17,18,Shaurya,Saxena,41,Male,UA944,Ahmedabad,Hong Kong,730,Economy,Confirmed,73.0,657.0,Adult,No,No
18,18,19,Tanvi,Chatterjee,48,Female,AI123,Lucknow,San Francisco,670,Economy,Confirmed,67.0,603.0,Senior,No,No
19,19,20,Arjun,Gupta,33,Male,QR567,Jaipur,Singapore,910,Business,Pending,91.0,819.0,Adult,No,Yes

In [133]:
	#Replace all ticket prices below ₹600 with 'Low Price'.
 #df["TicketPrice"]=df["TicketPrice"].apply(lambda i :"Low Price" if i<600  else i)

In [143]:
#Convert the 'TicketPrice' column to an integer type.
df["TicketPrice"]=df["TicketPrice"].astype(int)
df.dtypes

index             int64
PassengerID       int64
FirstName        object
LastName         object
Age               int64
Gender           object
FlightNumber     object
Departure        object
Destination      object
TicketPrice       int64
SeatClass        object
Status           object
Discount        float64
FinalPrice      float64
AgeGroup         object
HighValue        object
AboveAverage     object
dtype: object

In [144]:
#Create a new column 'AboveAverage' with 'Yes' if the ticket price is above the dataset's average.
df['AboveAverage']=df["TicketPrice"].apply(lambda i : "Yes" if i>df["TicketPrice"].mean() else "No")
df.head()

,index,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status,Discount,FinalPrice,AgeGroup,HighValue,AboveAverage
0,0,1,Aarav,Sharma,25,Male,AI101,Mumbai,London,500,Economy,Confirmed,50.0,450.0,Young,No,No
1,1,2,Vihaan,Verma,30,Male,BA202,Delhi,New York,750,Business,Cancelled,75.0,675.0,Adult,No,No
2,2,3,Vivaan,Patel,45,Male,DL303,Bangalore,Los Angeles,600,Economy,Confirmed,60.0,540.0,Adult,No,No
3,3,4,Anaya,Desai,28,Female,EK404,Chennai,Dubai,1200,First,Confirmed,120.0,1080.0,Young,Yes,Yes
4,4,5,Myra,Iyer,34,Female,QR505,Kolkata,Tokyo,900,Business,Pending,90.0,810.0,Adult,No,Yes

In [146]:
#Convert the 'SeatClass' column to a categorical data type.
df["SeatClass"]=df["SeatClass"].astype("category")
df.dtypes

index              int64
PassengerID        int64
FirstName         object
LastName          object
Age                int64
Gender            object
FlightNumber      object
Departure         object
Destination       object
TicketPrice        int64
SeatClass       category
Status            object
Discount         float64
FinalPrice       float64
AgeGroup          object
HighValue         object
AboveAverage      object
dtype: object

In [148]:
#Find the top 5 passengers with the highest ticket price.
df.nlargest(5,"TicketPrice")

,index,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status,Discount,FinalPrice,AgeGroup,HighValue,AboveAverage
12,12,13,Pari,Malhotra,50,Female,EK433,Bangalore,Los Angeles,1300,First,Confirmed,130.0,1170.0,Senior,Yes,Yes
3,3,4,Anaya,Desai,28,Female,EK404,Chennai,Dubai,1200,First,Confirmed,120.0,1080.0,Young,Yes,Yes
16,16,17,Krishna,Das,36,Male,SQ833,Pune,Rome,1150,Business,Pending,115.0,1035.0,Adult,Yes,Yes
7,7,8,Kabir,Rao,38,Male,SQ808,Ahmedabad,Hong Kong,1100,Business,Confirmed,110.0,990.0,Adult,Yes,Yes
15,15,16,Riya,Bose,23,Female,AF722,Hyderabad,Munich,970,First,Confirmed,97.0,873.0,Young,No,Yes

In [151]:
#Find the bottom 5 passengers with the lowest ticket price.
df.nsmallest(5,"TicketPrice")

,index,PassengerID,FirstName,LastName,Age,Gender,FlightNumber,Departure,Destination,TicketPrice,SeatClass,Status,Discount,FinalPrice,AgeGroup,HighValue,AboveAverage
0,0,1,Aarav,Sharma,25,Male,AI101,Mumbai,London,500,Economy,Confirmed,50.0,450.0,Young,No,No
11,11,12,Rudra,Chopra,26,Male,DL322,Delhi,New York,580,Economy,Cancelled,58.0,522.0,Young,No,No
2,2,3,Vivaan,Patel,45,Male,DL303,Bangalore,Los Angeles,600,Economy,Confirmed,60.0,540.0,Adult,No,No
9,9,10,Aadhya,Bhat,27,Female,AI110,Jaipur,Singapore,650,Economy,Confirmed,65.0,585.0,Young,No,No
18,18,19,Tanvi,Chatterjee,48,Female,AI123,Lucknow,San Francisco,670,Economy,Confirmed,67.0,603.0,Senior,No,No

In [155]:
#Save the modified DataFrame to a new CSV file.
df.to_csv("Modified_AirLine_Data.csv")