<a href="https://colab.research.google.com/github/DipaliDhonnar/python/blob/main/anime.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###*make a new column for episode count*
###*make a new column for time stamp*
###*which anime has the highest score*
###*give me top 5 highest scoring anime*
###*which anime has the highest episode count*
###*animes with top 5 episode count*
###*which is the longest running anime*

In [106]:
import numpy as np
import pandas as pd
df=pd.read_csv(r"anime.csv")
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [76]:
df.shape

(50, 3)

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rank    50 non-null     int64
 1   Title   50 non-null     object
 2   Score   50 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.3+ KB

In [78]:
df.describe()

           Rank     Score
count  50.00000  50.00000
mean   25.50000   8.88320
std    14.57738   0.11722
min     1.00000   8.71000
25%    13.25000   8.79000
50%    25.50000   8.85500
75%    37.75000   8.99000
max    50.00000   9.10000

In [79]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [80]:
def extract_episode(txt):
    check = False
    data = ""
    for i in txt:
        if i == ")":
            check = False
            return data
        if check == True:
            data = data + i
        if i == '(':
            check = True

In [81]:
df["episodes"]=df["Title"].apply(extract_episode)

In [82]:
df.head()

   Rank                                              Title  Score episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64 eps
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24 eps
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   13 eps
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06   51 eps
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05   10 eps

In [83]:
df["episodes"]=df['episodes'].str.replace(" eps","")

In [104]:
df["episodes"].astype(int).head()

0    64
1    24
2    13
3    51
4    10
Name: episodes, dtype: int64

In [86]:
#make a new column for time stamp
def extract_time_stamp(txt):
  check =False
  time=""
  for i in txt:
    if i ==")":
      check=True
    if check==True:
      time=time+i
  return(time[1:20])

In [87]:
df["time_stamp"]=df["Title"].apply(extract_time_stamp)
df.head()

,Rank,Title,Score,episodes,time_stamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [103]:
month_to_num = {
    'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6,
    'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12
}

def calculate_months_between(timestamp_str):
    parts = timestamp_str.split(' - ')
    if len(parts) != 2:
        return None # Handle malformed timestamps

    start_part = parts[0].strip()
    end_part = parts[1].strip()

    start_month_str, start_year_str = start_part.split(' ')
    end_month_str, end_year_str = end_part.split(' ')

    start_month_num = month_to_num.get(start_month_str, None)
    end_month_num = month_to_num.get(end_month_str, None)
    start_year = int(start_year_str)
    end_year = int(end_year_str)

    if start_month_num is None or end_month_num is None:
        return None # Handle unknown month abbreviations

    # Calculate total months inclusive of start and end month
    total_months = (end_year - start_year) * 12 + (end_month_num - start_month_num) + 1
    return total_months

df['num_months'] = df['time_stamp'].apply(calculate_months_between)

In [89]:
#df.drop("start_month_num" ,axis=1,inplace=True)

In [90]:
df.head()

,Rank,Title,Score,episodes,time_stamp,num_months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

In [91]:
df["Score"].max()

9.1

In [110]:
df["Score"].sort_values(ascending=False).head()

0    9.10
1    9.07
2    9.06
3    9.06
4    9.05
Name: Score, dtype: float64

In [98]:
df["episodes"].max()

'75'

In [100]:
df.sort_values(by="episodes",ascending=False).head()

,Rank,Title,Score,episodes,time_stamp,num_months
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,18
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,18
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017,1
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12

In [101]:
df[df["num_months"]==df["num_months"].max()].head()

,Rank,Title,Score,episodes,time_stamp,num_months
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111

In [102]:
df["num_months"].max()

111