<a href="https://colab.research.google.com/github/DipaliDhonnar/python/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [256]:
import numpy as np
import pandas as pd
labels=["a","b","c"]
my_list=[10,20,30]
my_array=np.array([10,20,30])
my_dist={"a":10,"b":20, "c":30}
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [257]:
pd.Series(my_array,index=labels)

a    10
b    20
c    30
dtype: int64

In [258]:
pd.Series(my_dist)

a    10
b    20
c    30
dtype: int64

In [259]:
# data frams
data={"name":["dipali","Rupali","Rutuja","varsha","ashwine"],"age":[21,18,10,20,16]}
pd.DataFrame(data)

      name  age
0   dipali   21
1   Rupali   18
2   Rutuja   10
3   varsha   20
4  ashwine   16

In [260]:
data_list=[["dipali",21],["Rupali",18],["Rutuja",10],["varsha",20],["ashwine",16]]
columns=["name","age"]
df=pd.DataFrame(data_list,columns=columns)

In [261]:
df

      name  age
0   dipali   21
1   Rupali   18
2   Rutuja   10
3   varsha   20
4  ashwine   16

In [262]:
df.shape

(5, 2)

In [263]:
df["name"]

0     dipali
1     Rupali
2     Rutuja
3     varsha
4    ashwine
Name: name, dtype: object

In [264]:
df[["name","age"]]

      name  age
0   dipali   21
1   Rupali   18
2   Rutuja   10
3   varsha   20
4  ashwine   16

In [265]:
df.iloc[0][["name","age"]]

name    dipali
age         21
Name: 0, dtype: object

In [266]:
df.loc[1]

name    Rupali
age         18
Name: 1, dtype: object

In [267]:
df.iloc[1]

name    Rupali
age         18
Name: 1, dtype: object

In [268]:
df["equcation"]=["eng","12th","3rd","iti","10th"]
df

      name  age equcation
0   dipali   21       eng
1   Rupali   18      12th
2   Rutuja   10       3rd
3   varsha   20       iti
4  ashwine   16      10th

In [269]:
df.drop("equcation",axis=1)

      name  age
0   dipali   21
1   Rupali   18
2   Rutuja   10
3   varsha   20
4  ashwine   16

In [270]:
df

      name  age equcation
0   dipali   21       eng
1   Rupali   18      12th
2   Rutuja   10       3rd
3   varsha   20       iti
4  ashwine   16      10th

In [271]:
df.drop("equcation",axis=1, inplace=True)

In [272]:
df

      name  age
0   dipali   21
1   Rupali   18
2   Rutuja   10
3   varsha   20
4  ashwine   16

In [273]:
df["city"]=["mumbai","pune","gova","thane","pune"]
df

      name  age    city
0   dipali   21  mumbai
1   Rupali   18    pune
2   Rutuja   10    gova
3   varsha   20   thane
4  ashwine   16    pune

In [274]:
df.loc[[1,2]][['name',"age"]]

     name  age
1  Rupali   18
2  Rutuja   10

In [275]:
df[df["age"]<20]

      name  age  city
1   Rupali   18  pune
2   Rutuja   10  gova
4  ashwine   16  pune

In [276]:
df[(df["age"]>20) & (df["city"]=="mumbai")]

     name  age    city
0  dipali   21  mumbai

In [277]:
data = {
    "Name": ["Amit", "Sneha", "Rahul", "Priya", "Akash", "Neha", "Rohit", "Pooja"],
    "Age": [22, None, 24, 21, None, 23, 25, None],
    "City": ["Pune", "Nashik", "Pune", "Mumbai", "Pune", None, "Nashik", "Mumbai"],
    "Salary": [25000, 30000, None, 28000, 35000, None, 40000, 32000],
    "Department": ["IT", None, "HR", "IT", None, "Finance", "IT", None]
}

In [278]:
df_missing_value=pd.DataFrame(data)
df_missing_value

    Name   Age    City   Salary Department
0   Amit  22.0    Pune  25000.0         IT
1  Sneha   NaN  Nashik  30000.0       None
2  Rahul  24.0    Pune      NaN         HR
3  Priya  21.0  Mumbai  28000.0         IT
4  Akash   NaN    Pune  35000.0       None
5   Neha  23.0    None      NaN    Finance
6  Rohit  25.0  Nashik  40000.0         IT
7  Pooja   NaN  Mumbai  32000.0       None

In [279]:
df_missing_value.isna()

    Name    Age   City  Salary  Department
0  False  False  False   False       False
1  False   True  False   False        True
2  False  False  False    True       False
3  False  False  False   False       False
4  False   True  False   False        True
5  False  False   True    True       False
6  False  False  False   False       False
7  False   True  False   False        True

In [280]:
df_missing_value.isna().sum()

Name          0
Age           3
City          1
Salary        2
Department    3
dtype: int64

In [281]:
df_missing_value.isna().any()

Name          False
Age            True
City           True
Salary         True
Department     True
dtype: bool

In [282]:
df_missing_value.dropna(axis=0)

    Name   Age    City   Salary Department
0   Amit  22.0    Pune  25000.0         IT
3  Priya  21.0  Mumbai  28000.0         IT
6  Rohit  25.0  Nashik  40000.0         IT

In [283]:
df_missing_value.dropna(thresh=4)

    Name   Age    City   Salary Department
0   Amit  22.0    Pune  25000.0         IT
2  Rahul  24.0    Pune      NaN         HR
3  Priya  21.0  Mumbai  28000.0         IT
6  Rohit  25.0  Nashik  40000.0         IT

In [284]:
df_missing_value

    Name   Age    City   Salary Department
0   Amit  22.0    Pune  25000.0         IT
1  Sneha   NaN  Nashik  30000.0       None
2  Rahul  24.0    Pune      NaN         HR
3  Priya  21.0  Mumbai  28000.0         IT
4  Akash   NaN    Pune  35000.0       None
5   Neha  23.0    None      NaN    Finance
6  Rohit  25.0  Nashik  40000.0         IT
7  Pooja   NaN  Mumbai  32000.0       None

In [285]:
df_missing_value.fillna(0)

    Name   Age    City   Salary Department
0   Amit  22.0    Pune  25000.0         IT
1  Sneha   0.0  Nashik  30000.0          0
2  Rahul  24.0    Pune      0.0         HR
3  Priya  21.0  Mumbai  28000.0         IT
4  Akash   0.0    Pune  35000.0          0
5   Neha  23.0       0      0.0    Finance
6  Rohit  25.0  Nashik  40000.0         IT
7  Pooja   0.0  Mumbai  32000.0          0

In [286]:
values={"Name":"Rutuja","Age":df_missing_value['Age'].mean(), "City":"Local","Salary":20000,"Department":"IT"}
df_missing_value.fillna(value=values)

    Name   Age    City   Salary Department
0   Amit  22.0    Pune  25000.0         IT
1  Sneha  23.0  Nashik  30000.0         IT
2  Rahul  24.0    Pune  20000.0         HR
3  Priya  21.0  Mumbai  28000.0         IT
4  Akash  23.0    Pune  35000.0         IT
5   Neha  23.0   Local  20000.0    Finance
6  Rohit  25.0  Nashik  40000.0         IT
7  Pooja  23.0  Mumbai  32000.0         IT

In [287]:
#mergiing in Pandas

employees = pd.DataFrame({
    "Emp_ID": [101, 102, 103, 104, 105],
    "Name": ["Amit", "Sneha", "Rahul", "Priya", "Akash"],
    "Dept_ID": [1, 2, 1, 3, 4]
})

print(employees)

   Emp_ID   Name  Dept_ID
0     101   Amit        1
1     102  Sneha        2
2     103  Rahul        1
3     104  Priya        3
4     105  Akash        4

In [288]:
departments = pd.DataFrame({
    "Dept_ID": [1, 2, 3, 5],
    "Department": ["IT", "HR", "Finance", "Marketing"],
    "Location": ["Pune", "Mumbai", "Nashik", "Delhi"]
})

print(departments)

   Dept_ID Department Location
0        1         IT     Pune
1        2         HR   Mumbai
2        3    Finance   Nashik
3        5  Marketing    Delhi

In [289]:
pd.merge(employees,departments,on="Dept_ID")

   Emp_ID   Name  Dept_ID Department Location
0     101   Amit        1         IT     Pune
1     102  Sneha        2         HR   Mumbai
2     103  Rahul        1         IT     Pune
3     104  Priya        3    Finance   Nashik

In [290]:
pd.merge(employees,departments,on="Dept_ID",how="outer")

   Emp_ID   Name  Dept_ID Department Location
0   101.0   Amit        1         IT     Pune
1   103.0  Rahul        1         IT     Pune
2   102.0  Sneha        2         HR   Mumbai
3   104.0  Priya        3    Finance   Nashik
4   105.0  Akash        4        NaN      NaN
5     NaN    NaN        5  Marketing    Delhi

In [291]:
pd.merge(employees,departments,on="Dept_ID",how="left")

   Emp_ID   Name  Dept_ID Department Location
0     101   Amit        1         IT     Pune
1     102  Sneha        2         HR   Mumbai
2     103  Rahul        1         IT     Pune
3     104  Priya        3    Finance   Nashik
4     105  Akash        4        NaN      NaN

In [292]:
pd.merge(employees,departments,on="Dept_ID",how="right")

   Emp_ID   Name  Dept_ID Department Location
0   101.0   Amit        1         IT     Pune
1   103.0  Rahul        1         IT     Pune
2   102.0  Sneha        2         HR   Mumbai
3   104.0  Priya        3    Finance   Nashik
4     NaN    NaN        5  Marketing    Delhi

In [293]:


jan = pd.DataFrame({
    "ID": [101, 102, 103],
    "Name": ["Amit", "Sneha", "Rahul"],
    "Salary": [25000, 30000, 28000]
    })
jan

    ID   Name  Salary
0  101   Amit   25000
1  102  Sneha   30000
2  103  Rahul   28000

In [294]:
feb = pd.DataFrame({
    "ID": [104, 105, 106],
    "Name": ["Priya", "Akash", "Neha"],
    "Salary": [32000, 35000, 29000]
})

feb

    ID   Name  Salary
0  104  Priya   32000
1  105  Akash   35000
2  106   Neha   29000

In [295]:
pd.concat([jan,feb], axis=1)

    ID   Name  Salary   ID   Name  Salary
0  101   Amit   25000  104  Priya   32000
1  102  Sneha   30000  105  Akash   35000
2  103  Rahul   28000  106   Neha   29000

In [296]:
employee = pd.DataFrame({
    "Name": ["Amit", "Sneha", "Rahul", "Priya", "Akash"],
    "Salary": [25000, 30000, 28000, 32000, 35000]
}, index=[101, 102, 103, 104, 105])

print(employee)

      Name  Salary
101   Amit   25000
102  Sneha   30000
103  Rahul   28000
104  Priya   32000
105  Akash   35000

In [297]:
department = pd.DataFrame({
    "Department": ["IT", "HR", "Finance", "IT", "Marketing"],
    "Location": ["Pune", "Mumbai", "Nashik", "Pune", "Delhi"]
}, index=[101, 102, 103, 104, 106])

print(department)

    Department Location
101         IT     Pune
102         HR   Mumbai
103    Finance   Nashik
104         IT     Pune
106  Marketing    Delhi

In [298]:
employee.join(department)

      Name  Salary Department Location
101   Amit   25000         IT     Pune
102  Sneha   30000         HR   Mumbai
103  Rahul   28000    Finance   Nashik
104  Priya   32000         IT     Pune
105  Akash   35000        NaN      NaN

In [299]:
employee.join(department,how="outer")

      Name   Salary Department Location
101   Amit  25000.0         IT     Pune
102  Sneha  30000.0         HR   Mumbai
103  Rahul  28000.0    Finance   Nashik
104  Priya  32000.0         IT     Pune
105  Akash  35000.0        NaN      NaN
106    NaN      NaN  Marketing    Delhi

In [300]:
employee.join(department,how="left")

      Name  Salary Department Location
101   Amit   25000         IT     Pune
102  Sneha   30000         HR   Mumbai
103  Rahul   28000    Finance   Nashik
104  Priya   32000         IT     Pune
105  Akash   35000        NaN      NaN

In [301]:
employee.join(department,how="right")

      Name   Salary Department Location
101   Amit  25000.0         IT     Pune
102  Sneha  30000.0         HR   Mumbai
103  Rahul  28000.0    Finance   Nashik
104  Priya  32000.0         IT     Pune
106    NaN      NaN  Marketing    Delhi

In [302]:
department.join(employee,how="right")

    Department Location   Name  Salary
101         IT     Pune   Amit   25000
102         HR   Mumbai  Sneha   30000
103    Finance   Nashik  Rahul   28000
104         IT     Pune  Priya   32000
105        NaN      NaN  Akash   35000

In [303]:
department.join(employee,how="right")

    Department Location   Name  Salary
101         IT     Pune   Amit   25000
102         HR   Mumbai  Sneha   30000
103    Finance   Nashik  Rahul   28000
104         IT     Pune  Priya   32000
105        NaN      NaN  Akash   35000

In [304]:
department.join(employee,how="inner")

    Department Location   Name  Salary
101         IT     Pune   Amit   25000
102         HR   Mumbai  Sneha   30000
103    Finance   Nashik  Rahul   28000
104         IT     Pune  Priya   32000

In [305]:


data = {
    "Name": ["Amit", "Sneha", "Rahul", "Priya", "Akash",
             "Neha", "Rohit", "Pooja", "Kiran", "Anjali"],

    "Department": ["IT", "HR", "IT", "Finance", "HR",
                   "IT", "Finance", "HR", "IT", "Finance"],

    "City": ["Pune", "Mumbai", "Pune", "Nashik", "Mumbai",
             "Nashik", "Pune", "Mumbai", "Pune", "Nashik"],

    "Salary": [30000, 28000, 35000, 32000, 30000,
               40000, 38000, 27000, 45000, 36000],

    "Experience": [1, 2, 3, 2, 1, 4, 5, 1, 6, 3]
}

group_by = pd.DataFrame(data)
group_by

     Name Department    City  Salary  Experience
0    Amit         IT    Pune   30000           1
1   Sneha         HR  Mumbai   28000           2
2   Rahul         IT    Pune   35000           3
3   Priya    Finance  Nashik   32000           2
4   Akash         HR  Mumbai   30000           1
5    Neha         IT  Nashik   40000           4
6   Rohit    Finance    Pune   38000           5
7   Pooja         HR  Mumbai   27000           1
8   Kiran         IT    Pune   45000           6
9  Anjali    Finance  Nashik   36000           3

In [306]:
#group by can not print direct data thaye having create object
da = group_by.groupby("Department")
da

In [307]:
#but we can access that   object usin for loop
for i,v in da:
   print(i)
   print(v)

Finance
     Name Department    City  Salary  Experience
3   Priya    Finance  Nashik   32000           2
6   Rohit    Finance    Pune   38000           5
9  Anjali    Finance  Nashik   36000           3
HR
    Name Department    City  Salary  Experience
1  Sneha         HR  Mumbai   28000           2
4  Akash         HR  Mumbai   30000           1
7  Pooja         HR  Mumbai   27000           1
IT
    Name Department    City  Salary  Experience
0   Amit         IT    Pune   30000           1
2  Rahul         IT    Pune   35000           3
5   Neha         IT  Nashik   40000           4
8  Kiran         IT    Pune   45000           6

In [308]:
group_by.groupby("Department")["Salary"].sum()

Department
Finance    106000
HR          85000
IT         150000
Name: Salary, dtype: int64

In [309]:
group_by.groupby(["Department","Experience"])["Salary"].mean()

Department  Experience
Finance     2             32000.0
            3             36000.0
            5             38000.0
HR          1             28500.0
            2             28000.0
IT          1             30000.0
            3             35000.0
            4             40000.0
            6             45000.0
Name: Salary, dtype: float64

In [310]:
group_by["Salary"].agg(["mean","std","max","min", "median","count","sum"])

mean       34100.000000
std         5762.908216
max        45000.000000
min        27000.000000
median     33500.000000
count         10.000000
sum       341000.000000
Name: Salary, dtype: float64

In [311]:


data = {
    "Date": ["2026-01-01","2026-01-02","2026-01-01","2026-01-02",
             "2026-01-03","2026-01-03","2026-01-04","2026-01-04"],
    "Name": ["Amit","Priya","Amit","Priya","Rahul","Amit","Priya","Rahul"],
    "Product": ["Laptop","Mobile","Mobile","Laptop","Laptop","Mobile","Mobile","Laptop"],
    "Category": ["Electronics","Electronics","Electronics","Electronics",
                 "smart laptop","Electronics","Elect","smart laptop"],
    "Sales": [50000,20000,25000,55000,60000,30000,22000,65000],
    "Quantity": [1,2,1,1,1,2,1,1]
}

df = pd.DataFrame(data)

print(df)

         Date   Name Product      Category  Sales  Quantity
0  2026-01-01   Amit  Laptop   Electronics  50000         1
1  2026-01-02  Priya  Mobile   Electronics  20000         2
2  2026-01-01   Amit  Mobile   Electronics  25000         1
3  2026-01-02  Priya  Laptop   Electronics  55000         1
4  2026-01-03  Rahul  Laptop  smart laptop  60000         1
5  2026-01-03   Amit  Mobile   Electronics  30000         2
6  2026-01-04  Priya  Mobile         Elect  22000         1
7  2026-01-04  Rahul  Laptop  smart laptop  65000         1

In [312]:
pivot = pd.pivot_table(
    df,
    values="Sales",
    index="Name",
    columns="Product",
    aggfunc="sum"
)

print(pivot)

Product    Laptop   Mobile
Name
Amit      50000.0  55000.0
Priya     55000.0  42000.0
Rahul    125000.0      NaN

In [313]:
pivot=pd.pivot_table(df,values=["Sales","Quantity"],index="Name",columns="Product",aggfunc="sum")
print(pivot)

        Quantity            Sales
Product   Laptop Mobile    Laptop   Mobile
Name
Amit         1.0    3.0   50000.0  55000.0
Priya        1.0    3.0   55000.0  42000.0
Rahul        2.0    NaN  125000.0      NaN

In [314]:


data = {
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Amit", "Priya", "Rahul", "Sneha"],
    "Department": ["IT", "HR", "IT", "Sales", "IT", "HR", "IT", "Sales"],
    "Salary": [45000, 40000, 50000, 35000, 48000, 42000, 55000, 38000],
    "Age": [25, 28, 24, 30, 26, 29, 25, 31],
    "Experience": [2, 4, 1, 5, 3, 5, 2, 6],
    "Performance": [85, 78, 90, 72, 88, 82, 95, 75]
}

operation = pd.DataFrame(data)

print(operation)

    Name Department  Salary  Age  Experience  Performance
0   Amit         IT   45000   25           2           85
1  Priya         HR   40000   28           4           78
2  Rahul         IT   50000   24           1           90
3  Sneha      Sales   35000   30           5           72
4   Amit         IT   48000   26           3           88
5  Priya         HR   42000   29           5           82
6  Rahul         IT   55000   25           2           95
7  Sneha      Sales   38000   31           6           75

In [315]:
operation.shape

(8, 6)

In [316]:
operation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         8 non-null      object
 1   Department   8 non-null      object
 2   Salary       8 non-null      int64
 3   Age          8 non-null      int64
 4   Experience   8 non-null      int64
 5   Performance  8 non-null      int64
dtypes: int64(4), object(2)
memory usage: 516.0+ bytes

In [317]:
operation.describe()

             Salary       Age  Experience  Performance
count      8.000000   8.00000    8.000000     8.000000
mean   44125.000000  27.25000    3.500000    83.125000
std     6664.136425   2.60494    1.772811     7.863796
min    35000.000000  24.00000    1.000000    72.000000
25%    39500.000000  25.00000    2.000000    77.250000
50%    43500.000000  27.00000    3.500000    83.500000
75%    48500.000000  29.25000    5.000000    88.500000
max    55000.000000  31.00000    6.000000    95.000000

In [318]:
operation["Age"]+10

0    35
1    38
2    34
3    40
4    36
5    39
6    35
7    41
Name: Age, dtype: int64

In [319]:
operation["Age"]

0    25
1    28
2    24
3    30
4    26
5    29
6    25
7    31
Name: Age, dtype: int64

In [320]:
def double_salary(x):
   return x*2
operation

    Name Department  Salary  Age  Experience  Performance
0   Amit         IT   45000   25           2           85
1  Priya         HR   40000   28           4           78
2  Rahul         IT   50000   24           1           90
3  Sneha      Sales   35000   30           5           72
4   Amit         IT   48000   26           3           88
5  Priya         HR   42000   29           5           82
6  Rahul         IT   55000   25           2           95
7  Sneha      Sales   38000   31           6           75

In [321]:
operation["Salary"]=operation["Salary"].apply(double_salary)
operation

    Name Department  Salary  Age  Experience  Performance
0   Amit         IT   90000   25           2           85
1  Priya         HR   80000   28           4           78
2  Rahul         IT  100000   24           1           90
3  Sneha      Sales   70000   30           5           72
4   Amit         IT   96000   26           3           88
5  Priya         HR   84000   29           5           82
6  Rahul         IT  110000   25           2           95
7  Sneha      Sales   76000   31           6           75